// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaceIntel.Api.Data;

#nullable disable

namespace RaceIntel.Api.Migrations
{
    [DbContext(typeof(RaceIntelDbContext))]
    partial class RaceIntelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaceIntel.Api.Data.Entities.NascarRaceListBasicYear", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Year"));

                    b.Property<DateTime>("PulledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Year");

                    b.ToTable("nascar_race_list_basic_year", (string)null);
                });

            modelBuilder.Entity("RaceIntel.Api.Data.Entities.NascarWeekendFeed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("PulledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year", "SeriesId", "RaceId")
                        .IsUnique();

                    b.ToTable("nascar_weekend_feed", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
